# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39dc89b9bf19c9a896f8738730046800e6b561e61069258d29ffa94d0da4df2d741dd82aecb931bf640b26967f8c385a5e5c279c16c67ea5263ad30b3215ee70

test:
  secret_key_base: aac0aaa6bc0e5273dea032644b4789aac9b552c844d71d9c403690859793b0cf28e565b3f8b894c7dcfb273f0905609479525f3b96692d4c8ebf9cc6b8b10d29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
